import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>RestCountries</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to RestCountries Next.js!
        </h1>

        <p className={styles.description}>
        Get information about countries via a Next.js API
          <code className={styles.code}> </code>
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>API Endpoints &rarr;</h2>
            <p>Below are described the REST endpoints available that you can use to search for countries</p>
            <br></br>

            <h2>All &rarr;</h2>
            <p>Load all the countries with all details</p>
            <a href="https://rest-countries-next-js-gilt.vercel.app/api/countries" target="_blank">https://rest-countries-next-js-gilt.vercel.app/api/countries</a>
            <br></br>

            <h2>Names List &rarr;</h2>
            <p>Get all country names</p>
            <a href="https://rest-countries-next-js-gilt.vercel.app/api/countries/names" target="_blank">https://rest-countries-next-js-gilt.vercel.app/api/countries/names</a>
           
            <h2>Names &rarr;</h2>
            <p>Get by country name.</p>
            <a href="https://rest-countries-next-js-gilt.vercel.app/api/countries/country?countryName=canada" target="_blank">https://rest-countries-next-js-gilt.vercel.app/api/countries/country?countryName=canada</a>
           
            <h2>Search by Name &rarr;</h2>
            <p>Search by country name. It will load countries which contain search characters</p>
            <a href="https://rest-countries-next-js-gilt.vercel.app/api/countries/search?name=land" target="_blank">https://rest-countries-next-js-gilt.vercel.app/api/countries/search?name=land</a>
           
            <h2>Capital City List &rarr;</h2>
            <p>Get all capital cities of all countries</p>
            <a href="https://rest-countries-next-js-gilt.vercel.app/api/countries/capitalcities" target="_blank">https://rest-countries-next-js-gilt.vercel.app/api/countries/capitalcities</a>
           
            </div>
       
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/Chamaxonline"
          target="_blank"
          rel="noopener noreferrer"
        >
          Follow me on Github{' '}
          <span className={styles.logo}>
            <Image src="/GitHub-Logo.png" alt="Vercel Logo" width={64} height={36} />
          </span>
        </a>
      </footer>
    </div>
  )
}
